// Auto-generated by WebMCP Auto-Instrumentor
// Do not edit manually — re-run `webmcp instrument` to regenerate
// Source hash: 9b2e527e76b1
// Generated without LLM — add OPENAI_API_KEY or run `gh auth login` for better handlers
// Requires: @webmcp/runtime — https://github.com/user/webmcp

// ── WebMCP DOM helpers ──────────────────────────────────────
function __mcpSetValue(selector, value) {
  const el = document.querySelector(selector);
  if (!el) throw new Error('[WebMCP] Element not found: ' + selector);
  // Use native setter to bypass React's value tracking
  const proto = el instanceof HTMLTextAreaElement
    ? HTMLTextAreaElement.prototype
    : HTMLInputElement.prototype;
  const nativeSetter = Object.getOwnPropertyDescriptor(proto, 'value')?.set;
  if (nativeSetter) {
    nativeSetter.call(el, value);
  } else {
    el.value = value;
  }
  el.dispatchEvent(new Event('input', { bubbles: true }));
  el.dispatchEvent(new Event('change', { bubbles: true }));
}

function __mcpSetChecked(selector, checked) {
  const el = document.querySelector(selector);
  if (!el) throw new Error('[WebMCP] Element not found: ' + selector);
  const nativeSetter = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'checked')?.set;
  if (nativeSetter) nativeSetter.call(el, checked);
  else el.checked = checked;
  el.dispatchEvent(new Event('change', { bubbles: true }));
}

function __mcpSetSelect(selector, value) {
  const el = document.querySelector(selector);
  if (!el) throw new Error('[WebMCP] Element not found: ' + selector);
  el.value = value;
  el.dispatchEvent(new Event('change', { bubbles: true }));
}

function __mcpClick(selector) {
  const el = document.querySelector(selector);
  if (!el) throw new Error('[WebMCP] Element not found: ' + selector);
  el.click();
}
// ────────────────────────────────────────────────────────────


window.mcp.registerTool({
  name: "save_changes_settings_page",
  description: "Save Changes the form with: Display name",
  inputSchema: {
    type: "object",
    properties: {
        "display_name": {
            "type": "string",
            "description": "Display name"
        }
    },
    required: []
  },
  handler: async (params) => {
    try {
      __mcpSetValue('#display-name', params.display_name);
      // Small delay to let React process state updates
      await new Promise(r => setTimeout(r, 100));
      __mcpClick('input[type="submit"]');
      return { success: true, message: 'Action completed successfully' };
    } catch (err) {
      return { success: false, message: err instanceof Error ? err.message : String(err) };
    }
  }
});

window.mcp.registerTool({
  name: "export_my_data",
  description: "Trigger: Export My Data",
  inputSchema: {
    type: "object",
    properties: {},
    required: []
  },
  handler: async (params) => {
    try {
      // Small delay to let React process state updates
      await new Promise(r => setTimeout(r, 100));
      __mcpClick('/* TODO: add id or data-testid to this button element */');
      return { success: true, message: 'Action completed successfully' };
    } catch (err) {
      return { success: false, message: err instanceof Error ? err.message : String(err) };
    }
  }
});
