import { describe, it, expect } from 'vitest';
import { generateMCPCodeSync } from '../src/generator/code-generator.js';
import { FRAMEWORK_HELPERS } from '../src/generator/framework-helpers.js';
import { parseFile } from '../src/parser/index.js';
import { buildProposals } from '../src/proposal/index.js';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const fixturesDir = resolve(__dirname, '../../../tests/fixtures/react');

function loadProposals(fixture: string) {
    const source = readFileSync(resolve(fixturesDir, fixture), 'utf-8');
    const analysis = parseFile(source, fixture);
    return { analysis, proposals: buildProposals(analysis) };
}

// ── generateMCPCodeSync ───────────────────────────────────────

describe('generateMCPCodeSync', () => {
    it('includes FRAMEWORK_HELPERS in the output', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        // Check for a distinctive marker from the helpers
        expect(code).toContain('__mcpSetValue');
        expect(code).toContain('__mcpClick');
    });

    it('calls window.mcp.registerTool for each selected tool', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        const count = (code.match(/window\.mcp\.registerTool/g) ?? []).length;
        expect(count).toBe(proposals.length);
    });

    it('uses the correct tool name', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        expect(code).toContain(proposals[0].name);
    });

    it('includes JSON schema properties in the output', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        // ContactForm has name, email, message fields
        expect(code).toContain('"name"');
    });

    it('generates handler with __mcpSetValue for ContactForm inputs', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        expect(code).toContain('__mcpSetValue');
    });

    it('generates handler with try/catch block', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        expect(code).toContain('try {');
        expect(code).toContain('catch (err)');
    });

    it('SettingsPage: generates 2 tools when destructive excluded', () => {
        const { analysis, proposals } = loadProposals('SettingsPage.tsx');
        const selected = proposals.filter(p => p.risk !== 'destructive');
        const code = generateMCPCodeSync(selected, { format: 'iife', framework: analysis.framework });
        const count = (code.match(/window\.mcp\.registerTool/g) ?? []).length;
        expect(count).toBe(2);
    });

    it('matches snapshot for complete generated code (ContactForm)', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        // Stable snapshot requires removing the hash which changes based on content/tools selected,
        // though the hash implementation here is deterministic since the tools are stable.
        expect(code).toMatchSnapshot();
    });

    it('emits the auto-generated header comment', () => {
        const { analysis, proposals } = loadProposals('ContactForm.tsx');
        const code = generateMCPCodeSync(proposals, { format: 'iife', framework: analysis.framework });
        expect(code).toContain('Auto-generated by WebMCP Auto-Instrumentor');
    });
});
